# Generated by Django 3.2.19 on 2023-06-29 14:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meldingen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "naam",
                    models.CharField(
                        choices=[
                            ("openstaand", "Openstaand"),
                            ("in_behandeling", "In behandeling"),
                            ("controle", "Controle"),
                            ("afgehandeld", "Afgehandeld"),
                        ],
                        default="openstaand",
                        max_length=50,
                    ),
                ),
                (
                    "melding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statussen_voor_melding",
                        to="meldingen.melding",
                    ),
                ),
            ],
            options={
                "ordering": ("-aangemaakt_op",),
            },
        ),
    ]
