# Generated by Django 3.2.19 on 2023-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="naam",
            field=models.CharField(
                choices=[
                    ("openstaand", "Openstaand"),
                    ("in_behandeling", "In behandeling"),
                    ("controle", "Controle"),
                    ("afgehandeld", "Afgehandeld"),
                    ("geannuleerd", "Geannuleerd"),
                ],
                default="openstaand",
                max_length=50,
            ),
        ),
    ]
