# Generated by Django 3.2.19 on 2024-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0002_alter_status_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="naam",
            field=models.CharField(
                choices=[
                    ("openstaand", "Openstaand"),
                    ("in_behandeling", "In behandeling"),
                    ("controle", "Controle"),
                    ("afgehandeld", "Afgehandeld"),
                    ("geannuleerd", "Geannuleerd"),
                    ("wachten_melder", "Wachten melder"),
                    ("pauze", "Pauze"),
                ],
                default="openstaand",
                max_length=50,
            ),
        ),
    ]
