# Generated by Django 3.2.18 on 2023-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0003_alter_status_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="naam",
            field=models.CharField(
                choices=[
                    ("openstaand", "Openstaand"),
                    ("in_behandeling", "In behandeling"),
                    ("afgehandeld", "Afgehandeld"),
                ],
                default="openstaand",
                max_length=50,
            ),
        ),
    ]
