# Generated by Django 3.2.18 on 2023-05-15 18:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meldingen", "0017_delete_onderwerpalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Taakapplicatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("naam", models.CharField(default="Taakapplicatie", max_length=100)),
                (
                    "gebruiker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taakapplicatie_voor_gebruiker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "melding_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taakapplicatie_voor_melding_context",
                        to="meldingen.meldingcontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
