# Generated by Django 3.2.18 on 2023-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliassen", "0002_auto_20230505_2034"),
        ("applicaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakapplicatie",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                related_name="taakapplicaties_voor_onderwerpen",
                to="aliassen.OnderwerpAlias",
            ),
        ),
    ]
