# Generated by Django 3.2.19 on 2024-01-30 21:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="valide_basis_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), default=list, size=None
            ),
        ),
    ]
