# Generated by Django 3.2.18 on 2023-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicaties", "0002_taakapplicatie_onderwerpen"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakapplicatie",
            name="basis_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
