# Generated by Django 4.2.15 on 2024-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0003_auto_20241009_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_gebruiker_token_timeout",
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_type",
            field=models.CharField(
                choices=[
                    ("taakapplicatie", "Taakapplicatie"),
                    ("signaalapplicatie", "Signaalapplicatie"),
                ],
                default="taakapplicatie",
            ),
        ),
    ]
