# Generated by Django 3.2.19 on 2023-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicaties", "0003_taakapplicatie_basis_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakapplicatie",
            name="taaktypes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
