# Generated by Django 3.2.19 on 2023-06-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applicaties", "0005_applicatie"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO applicaties_applicatie_onderwerpen (
                id,
                applicatie_id,
                onderwerpalias_id
            )
            SELECT
                id,
                taakapplicatie_id,
                onderwerpalias_id
            FROM
                applicaties_taakapplicatie_onderwerpen;
            SELECT setval(pg_get_serial_sequence('"applicaties_applicatie_onderwerpen"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "applicaties_applicatie_onderwerpen";

            INSERT INTO applicaties_applicatie (
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                naam,
                basis_url,
                gebruiker_id,
                taaktypes,
                melding_context_id
            )
            SELECT
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                naam,
                basis_url,
                gebruiker_id,
                taaktypes,
                melding_context_id
            FROM
                applicaties_taakapplicatie;
            SELECT setval(pg_get_serial_sequence('"applicaties_applicatie"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "applicaties_applicatie";
        """,
            reverse_sql="""
            INSERT INTO applicaties_taakapplicatie_onderwerpen (
                id,
                taakapplicatie_id,
                onderwerpalias_id
            )
            SELECT
                id,
                applicatie_id,
                onderwerpalias_id
            FROM
                applicaties_applicatie_onderwerpen;

            INSERT INTO applicaties_taakapplicatie (
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                naam,
                basis_url,
                gebruiker_id,
                taaktypes,
                melding_context_id
            )
            SELECT
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                naam,
                basis_url,
                gebruiker_id,
                taaktypes,
                melding_context_id
            FROM
                applicaties_applicatie;
        """,
        )
    ]
