# Generated by Django 3.2.19 on 2023-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicaties", "0007_auto_20230608_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicatie",
            name="applicatie_gebruiker_naam",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
