# Generated by Django 3.2.18 on 2023-04-19 11:31

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0006_auto_20230418_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeldingContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("naam", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "onderwerpen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300), size=None
                    ),
                ),
                ("veld_waardes", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="signaal",
            name="onderwerpen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="melding",
            name="melding_context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldingen_voor_meldingcontext",
                to="mor.meldingcontext",
            ),
        ),
    ]
