# Generated by Django 3.2.18 on 2023-04-24 08:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0009_alter_meldingcontext_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnderwerpAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("bron_url", models.CharField(max_length=500)),
                ("response_json", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Onderwerp alias",
                "verbose_name_plural": "Onderwerp aliassen",
            },
        ),
        migrations.RemoveField(
            model_name="meldingcontext",
            name="onderwerpen",
        ),
        migrations.AddField(
            model_name="meldingcontext",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="meldingcontexten_voor_onderwerpen",
                to="mor.OnderwerpAlias",
            ),
        ),
    ]
