# Generated by Django 3.2.18 on 2023-05-16 19:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicaties", "0002_taakapplicatie_onderwerpen"),
        ("meldingen", "0018_auto_20230516_2132"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taakopdracht",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("taaktype", models.CharField(max_length=200)),
                ("bericht", models.CharField(blank=True, max_length=500, null=True)),
                ("laatst_ontvangen_update", models.DateTimeField()),
                ("additionele_informatie", models.JSONField(default=dict)),
                ("taak_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "melding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakopdrachten_voor_melding",
                        to="meldingen.melding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taakopdracht",
                "verbose_name_plural": "Taakopdrachten",
                "ordering": ("-aangemaakt_op",),
            },
        ),
        migrations.CreateModel(
            name="Taakstatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "naam",
                    models.CharField(
                        choices=[
                            ("nieuw", "Nieuw"),
                            ("bezig", "Bezig"),
                            ("voltooid", "Voltooid"),
                        ],
                        default="nieuw",
                        max_length=50,
                    ),
                ),
                (
                    "taakopdracht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakstatussen_voor_taakopdracht",
                        to="taken.taakopdracht",
                    ),
                ),
            ],
            options={
                "ordering": ("-aangemaakt_op",),
            },
        ),
        migrations.AddField(
            model_name="taakopdracht",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taakopdrachten_voor_taakstatus",
                to="taken.taakstatus",
            ),
        ),
        migrations.AddField(
            model_name="taakopdracht",
            name="taakapplicatie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taakopdrachten_voor_taakapplicatie",
                to="applicaties.taakapplicatie",
            ),
        ),
        migrations.CreateModel(
            name="Taakgebeurtenis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "omschrijving_intern",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "taakopdracht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taakgebeurtenissen_voor_taakopdracht",
                        to="taken.taakopdracht",
                    ),
                ),
                (
                    "taakstatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taakgebeurtenissen_voor_taakstatus",
                        to="taken.taakstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Melding gebeurtenis",
                "verbose_name_plural": "Melding gebeurtenissen",
                "ordering": ("-aangemaakt_op",),
            },
        ),
    ]
