# Generated by Django 3.2.18 on 2023-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="titel",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
