# Generated by Django 3.2.18 on 2023-05-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0002_taakopdracht_titel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taakopdracht",
            name="laatst_ontvangen_update",
        ),
    ]
