# Generated by Django 3.2.19 on 2023-05-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0003_remove_taakopdracht_laatst_ontvangen_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taakgebeurtenis",
            options={
                "ordering": ("-aangemaakt_op",),
                "verbose_name": "Taakgebeurtenis",
                "verbose_name_plural": "Taakgebeurtenissen",
            },
        ),
    ]
