# Generated by Django 3.2.19 on 2023-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0004_alter_taakgebeurtenis_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="afgesloten_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taakopdracht",
            name="resolutie",
            field=models.CharField(
                choices=[("opgelost", "Opgelost"), ("niet_opgelost", "Niet opgelost")],
                default="niet_opgelost",
                max_length=50,
            ),
        ),
    ]
