# Generated by Django 3.2.19 on 2023-11-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0004_alter_taakstatus_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="additionele_informatie",
            field=models.JSONField(default=dict),
        ),
    ]
