# Generated by Django 3.2.19 on 2023-06-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0005_auto_20230531_1523"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taakopdracht",
            old_name="taakapplicatie",
            new_name="applicatie",
        ),
    ]
