# Generated by Django 3.2.19 on 2023-12-14 16:32

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0006_alter_taakopdracht_resolutie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakgebeurtenis",
            name="additionele_informatie",
            field=utils.fields.DictJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="taakopdracht",
            name="additionele_informatie",
            field=utils.fields.DictJSONField(default=dict),
        ),
    ]
