# Generated by Django 3.2.19 on 2023-06-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicaties", "0006_auto_20230602_1526"),
        ("taken", "0006_rename_taakapplicatie_taakopdracht_applicatie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakopdracht",
            name="applicatie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taakopdrachten_voor_taakapplicatie",
                to="applicaties.applicatie",
            ),
        ),
    ]
