# Generated by Django 3.2.19 on 2023-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0008_alter_taakopdracht_applicatie"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakgebeurtenis",
            name="gebruiker",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
