# Generated by Django 4.2.15 on 2024-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0011_alter_taakopdracht_bericht"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taakopdracht",
            name="titel",
            field=models.CharField(max_length=200),
        ),
    ]
