# Generated by Django 3.2.18 on 2023-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_remove_status_omschrijving"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ("-aangemaakt_op",)},
        ),
    ]
