# Generated by Django 3.2.19 on 2023-06-29 14:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnderwerpGroep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("naam",)
                    ),
                ),
            ],
            options={
                "verbose_name": "Onderwerp groep",
                "verbose_name_plural": "Onderwerp groepen",
                "unique_together": {("slug",)},
            },
        ),
        migrations.CreateModel(
            name="Onderwerp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("naam",)
                    ),
                ),
                (
                    "onderwerp_groep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classificatie.onderwerpgroep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onderwerp",
                "verbose_name_plural": "Onderwerpen",
                "unique_together": {("slug", "onderwerp_groep")},
            },
        ),
    ]
