# Generated by Django 3.2.18 on 2023-04-18 09:10

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classificatie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnderwerpGroep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("naam",)
                    ),
                ),
            ],
            options={
                "verbose_name": "Onderwerp groep",
                "verbose_name_plural": "Onderwerp groepen",
                "unique_together": {("slug",)},
            },
        ),
        migrations.AddField(
            model_name="onderwerp",
            name="onderwerp_groep",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classificatie.onderwerpgroep",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="onderwerp",
            unique_together={("slug", "onderwerp_groep")},
        ),
    ]
