# Generated by Django 3.2.19 on 2024-02-27 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classificatie", "0003_auto_20230918_1426"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onderwerpgroep",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Onderwerp",
        ),
        migrations.DeleteModel(
            name="OnderwerpGroep",
        ),
    ]
