# Generated by Django 3.2.18 on 2023-03-28 07:59

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "locatie_type",
                    models.CharField(
                        choices=[
                            ("adres", "adres"),
                            ("lichtmast", "lichtmast"),
                            ("graf", "graf"),
                        ],
                        default="adres",
                        max_length=50,
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("bron", models.CharField(blank=True, max_length=50, null=True)),
                ("naam", models.CharField(blank=True, max_length=255, null=True)),
                ("straatnaam", models.CharField(blank=True, max_length=255, null=True)),
                ("huisnummer", models.IntegerField(blank=True, null=True)),
                ("huisletter", models.CharField(blank=True, max_length=1, null=True)),
                ("toevoeging", models.CharField(blank=True, max_length=4, null=True)),
                ("postcode", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "lichtmast_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plaatsnaam", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "begraafplaats",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("grafnummer", models.CharField(blank=True, max_length=10, null=True)),
                ("vak", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Geometrie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("locatie.locatie",),
        ),
        migrations.CreateModel(
            name="Graf",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("locatie.locatie",),
        ),
        migrations.CreateModel(
            name="Lichtmast",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("locatie.locatie",),
        ),
    ]
