# Generated by Django 3.2.18 on 2023-02-20 14:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Melding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aangemaakt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeldingGebeurtenis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aangemaakt", models.DateTimeField(auto_now_add=True)),
                (
                    "melding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melding_gebeurtenissen",
                        to="mor.melding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaakApplicatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(default="Taak applicatie", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Signaal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verwijzing", models.TextField()),
                (
                    "melding",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalen",
                        to="mor.melding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeldingGebeurtenisType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_naam",
                    models.CharField(
                        choices=[
                            (
                                "proccess_proposal_item_completion",
                                "proccess_proposal_item_completion",
                            ),
                            ("incident_handler_change", "incident_handler_change"),
                            ("status_change", "status_change"),
                            ("meta_data_change", "meta_data_change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                (
                    "incident_gebeurtenis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melding_gebeurtenistypes",
                        to="mor.meldinggebeurtenis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="melding",
            name="taak_applicaties",
            field=models.ManyToManyField(
                related_name="meldingen", to="mor.TaakApplicatie"
            ),
        ),
        migrations.CreateModel(
            name="Geometrie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                ("meta", models.JSONField(default=dict)),
                (
                    "melding",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometrieen",
                        to="mor.melding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bestand",
                    models.FileField(max_length=255, upload_to="attachments/%Y/%m/%d/"),
                ),
                ("mimetype", models.CharField(max_length=30)),
                ("is_afbeelding", models.BooleanField(default=False)),
                (
                    "incident_gebeurtenis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlages",
                        to="mor.meldinggebeurtenis",
                    ),
                ),
            ],
        ),
    ]
