# Generated by Django 3.2.18 on 2023-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
