# Generated by Django 3.2.18 on 2023-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0002_melding_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="melder",
            name="naam",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
