# Generated by Django 3.2.18 on 2023-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0003_melder_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="afgesloten_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
