# Generated by Django 3.2.18 on 2023-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mor", "0010_auto_20230424_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldingcontext",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                related_name="meldingcontexten_voor_onderwerpen",
                to="mor.OnderwerpAlias",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpalias",
            name="response_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
