# Generated by Django 3.2.18 on 2023-05-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aliassen", "0001_initial"),
        ("meldingen", "0015_alter_meldinggebeurtenis_gebeurtenis_type"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO aliassen_onderwerpalias (
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                bron_url,
                response_json
            )
            SELECT
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                bron_url,
                response_json
            FROM
                meldingen_onderwerpalias;

            SELECT setval(pg_get_serial_sequence('"aliassen_onderwerpalias"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "aliassen_onderwerpalias";
        """,
            reverse_sql="""
            INSERT INTO meldingen_onderwerpalias (
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                bron_url,
                response_json
            )
            SELECT
                id,
                uuid,
                aangemaakt_op,
                aangepast_op,
                bron_url,
                response_json
            FROM
                aliassen_onderwerpalias;
        """,
        )
    ]
