# Generated by Django 3.2.19 on 2023-06-29 14:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aliassen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Melding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("origineel_aangemaakt", models.DateTimeField()),
                ("omschrijving_kort", models.CharField(max_length=500)),
                (
                    "omschrijving",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("afgesloten_op", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(default=dict)),
                ("meta_uitgebreid", models.JSONField(default=dict)),
                (
                    "resolutie",
                    models.CharField(
                        choices=[
                            ("opgelost", "Opgelost"),
                            ("niet_opgelost", "Niet opgelost"),
                        ],
                        default="niet_opgelost",
                        max_length=50,
                    ),
                ),
                (
                    "onderwerpen",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meldingen_voor_onderwerpen",
                        to="aliassen.OnderwerpAlias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Melding",
                "verbose_name_plural": "Meldingen",
            },
        ),
        migrations.CreateModel(
            name="Meldinggebeurtenis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                (
                    "gebeurtenis_type",
                    models.CharField(
                        choices=[
                            ("standaard", "Standaard"),
                            ("status_wijziging", "Status wijziging"),
                            ("melding_aangemaakt", "Melding aangemaakt"),
                            ("taakopdracht_aangemaakt", "Taakopdracht aangemaakt"),
                            (
                                "taakopdracht_status_wijziging",
                                "Taakopdracht status wijziging",
                            ),
                        ],
                        default="standaard",
                        max_length=40,
                    ),
                ),
                (
                    "omschrijving_intern",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "omschrijving_extern",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("gebruiker", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "melding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meldinggebeurtenissen_voor_melding",
                        to="meldingen.melding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Melding gebeurtenis",
                "verbose_name_plural": "Melding gebeurtenissen",
                "ordering": ("-aangemaakt_op",),
            },
        ),
    ]
