# Generated by Django 3.2.18 on 2023-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bijlage",
            name="afbeelding_verkleind",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="attachments/%Y/%m/%d/cropped/",
            ),
        ),
    ]
