# Generated by Django 3.2.19 on 2023-06-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_initial"),
        ("taken", "0001_initial"),
        ("meldingen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melding_voor_status",
                to="status.status",
            ),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldinggebeurtenis_voor_status",
                to="status.status",
            ),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="taakgebeurtenis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_taakgebeurtenis",
                to="taken.taakgebeurtenis",
            ),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="taakopdracht",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_taakopdracht",
                to="taken.taakopdracht",
            ),
        ),
    ]
