# Generated by Django 3.2.19 on 2023-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0002_auto_20230629_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="omschrijving_extern",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
