# Generated by Django 3.2.18 on 2023-03-29 14:22

import utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0002_bijlage_afbeelding_verkleind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bijlage",
            name="afbeelding_verkleind",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=utils.images.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="bijlage",
            name="bestand",
            field=models.FileField(
                max_length=255, upload_to=utils.images.get_upload_path
            ),
        ),
    ]
