# Generated by Django 3.2.19 on 2023-11-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locatie", "0003_auto_20231120_1259"),
        ("meldingen", "0003_alter_meldinggebeurtenis_omschrijving_extern"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="locatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_locatie",
                to="locatie.adres",
            ),
        ),
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_wijziging", "Status wijziging"),
                    ("melding_aangemaakt", "Melding aangemaakt"),
                    ("taakopdracht_aangemaakt", "Taakopdracht aangemaakt"),
                    ("taakopdracht_status_wijziging", "Taakopdracht status wijziging"),
                    ("locatie_aangemaakt", "Locatie aangemaakt"),
                ],
                default="standaard",
                max_length=40,
            ),
        ),
    ]
