# Generated by Django 3.2.18 on 2023-04-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
        ("meldingen", "0004_melding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="omschrijving",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melding_gebeurtenis_voor_status",
                to="status.status",
            ),
        ),
        migrations.AlterField(
            model_name="melding",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melding_voor_status",
                to="status.status",
            ),
        ),
        migrations.AlterField(
            model_name="signaal",
            name="melding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signalen_voor_melding",
                to="meldingen.melding",
            ),
        ),
    ]
