# Generated by Django 3.2.19 on 2023-11-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locatie", "0003_auto_20231120_1259"),
        ("meldingen", "0004_auto_20231123_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="locatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_locatie",
                to="locatie.locatie",
            ),
        ),
    ]
