# Generated by Django 3.2.18 on 2023-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0005_auto_20230412_0909"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bijlage",
            options={"verbose_name": "Bijlage", "verbose_name_plural": "Bijlagen"},
        ),
        migrations.AlterModelOptions(
            name="melder",
            options={"verbose_name": "Melder", "verbose_name_plural": "Melders"},
        ),
        migrations.AlterModelOptions(
            name="melding",
            options={"verbose_name": "Melding", "verbose_name_plural": "Meldingen"},
        ),
        migrations.AlterModelOptions(
            name="meldinggebeurtenis",
            options={
                "verbose_name": "Melding gebeurtenis",
                "verbose_name_plural": "Melding gebeurtenissen",
            },
        ),
        migrations.AlterModelOptions(
            name="signaal",
            options={"verbose_name": "Signaal", "verbose_name_plural": "Signalen"},
        ),
    ]
