# Generated by Django 3.2.19 on 2024-02-12 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0007_datawarehouse"),
    ]

    operations = [migrations.RunSQL("")]
