# Generated by Django 3.2.18 on 2023-04-19 15:45

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0008_auto_20230419_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldingcontext",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                overwrite=True,
                populate_from=("naam",),
                unique=True,
            ),
        ),
    ]
