# Generated by Django 3.2.19 on 2024-02-27 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0008_datawarehouse"),
        ("meldingen", "0009_auto_20240219_1818"),
    ]

    operations = []
