# Generated by Django 3.2.19 on 2024-02-27 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0010_merge_0008_datawarehouse_0009_auto_20240219_1818"),
        ("taken", "0005_taakgebeurtenis_additionele_informatie"),
    ]

    operations = [
        # dwh_meldingen_melding
        # remove privacy information from meta fields
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_meldingen_melding
                AS SELECT
                    id,
                    uuid,
                    aangemaakt_op,
                    aangepast_op,
                    origineel_aangemaakt,
                    omschrijving_kort,
                    omschrijving,
                    afgesloten_op,
                    meta - 'melderNaamField' - 'melderEmailField' - 'melderTelefoonField',
                    resolutie,
                    status_id,
                    urgentie
                FROM meldingen_melding
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_meldingen_melding TO dwh;"),
        # dwh_meldingen_melding_onderwerpen
        # combine with other table
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_meldingen_melding_onderwerpen
                AS SELECT
                    mmo.*,
                    ao.uuid,
                    ao.bron_url
                FROM meldingen_melding_onderwerpen AS mmo
                JOIN aliassen_onderwerpalias AS ao ON mmo.onderwerpalias_id = ao.id
            ;"""
        ),
        migrations.RunSQL(
            "GRANT SELECT ON TABLE dwh_meldingen_melding_onderwerpen TO dwh;"
        ),
        # dwh_locatie_locatie
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_locatie_locatie
                AS SELECT
                    *
                FROM locatie_locatie
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_locatie_locatie TO dwh;"),
        # dwh_status_status
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_status_status
                AS SELECT
                    *
                FROM status_status
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_status_status TO dwh;"),
        # dwh_meldingen_meldinggebeurtenis
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_meldingen_meldinggebeurtenis
                AS SELECT
                    *
                FROM meldingen_meldinggebeurtenis
            ;"""
        ),
        migrations.RunSQL(
            "GRANT SELECT ON TABLE dwh_meldingen_meldinggebeurtenis TO dwh;"
        ),
        # dwh_taken_taakgebeurtenis
        # remove information about employees
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_taken_taakgebeurtenis
                AS SELECT
                    id,
                    uuid,
                    aangemaakt_op,
                    aangepast_op,
                    omschrijving_intern,
                    taakopdracht_id,
                    taakstatus_id,
                    additionele_informatie
                FROM taken_taakgebeurtenis
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_taken_taakgebeurtenis TO dwh;"),
        # dwh_taken_taakopdracht
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_taken_taakopdracht
                AS SELECT
                    *
                FROM taken_taakopdracht
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_taken_taakopdracht TO dwh;"),
        # dwh_taken_taakstatus
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW dwh_taken_taakstatus
                AS SELECT
                    *
                FROM taken_taakstatus
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_taken_taakstatus TO dwh;"),
    ]
