# Generated by Django 3.2.18 on 2023-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0012_melding_onderwerpen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meldinggebeurtenis",
            old_name="omschrijving",
            new_name="omschrijving_intern",
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_verandering", "Status verandering"),
                    ("melding_aangemaakt", "Melding_aangemaakt"),
                ],
                default="standaard",
                max_length=20,
            ),
        ),
    ]
