# Generated by Django 3.2.18 on 2023-05-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0013_auto_20230504_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="omschrijving_extern",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
