# Generated by Django 3.2.19 on 2024-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0013_auto_20240327_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="melding",
            name="omschrijving_melder",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
