# Generated by Django 3.2.18 on 2023-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0014_meldinggebeurtenis_omschrijving_extern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_verandering", "Status verandering"),
                    ("melding_aangemaakt", "Melding aangemaakt"),
                ],
                default="standaard",
                max_length=20,
            ),
        ),
    ]
