# Generated by Django 3.2.19 on 2024-03-28 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0014_alter_melding_omschrijving_melder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="melding",
            name="aanvullende_informatie",
        ),
        migrations.RemoveField(
            model_name="melding",
            name="aanvullende_vragen",
        ),
        migrations.RemoveField(
            model_name="melding",
            name="omschrijving_melder",
        ),
    ]
