# Generated by Django 3.2.18 on 2023-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliassen", "0002_auto_20230505_2034"),
        ("meldingen", "0015_alter_meldinggebeurtenis_gebeurtenis_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meldinggebeurtenis",
            options={
                "ordering": ("-aangemaakt_op",),
                "verbose_name": "Melding gebeurtenis",
                "verbose_name_plural": "Melding gebeurtenissen",
            },
        ),
        migrations.AlterField(
            model_name="melding",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                related_name="meldingen_voor_onderwerpen",
                to="aliassen.OnderwerpAlias",
            ),
        ),
        migrations.AlterField(
            model_name="meldingcontext",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                related_name="meldingcontexten_voor_onderwerpen",
                to="aliassen.OnderwerpAlias",
            ),
        ),
    ]
