# Generated by Django 3.2.19 on 2024-09-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0016_alter_meldinggebeurtenis_gebeurtenis_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_wijziging", "Status wijziging"),
                    ("melding_aangemaakt", "Melding aangemaakt"),
                    ("taakopdracht_aangemaakt", "Taakopdracht aangemaakt"),
                    ("taakopdracht_verwijderd", "Taakopdracht verwijderd"),
                    ("taakopdracht_notificatie", "Taakopdracht notificatie"),
                    ("taakopdracht_status_wijziging", "Taakopdracht status wijziging"),
                    ("locatie_aangemaakt", "Locatie aangemaakt"),
                    ("signaal_toegevoegd", "Signaal toegevoegd"),
                    ("urgentie_aangepast", "Urgentie aangepast"),
                    ("melding_heropend", "Melding heropend"),
                ],
                default="standaard",
                max_length=40,
            ),
        ),
    ]
