# Generated by Django 3.2.18 on 2023-05-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0016_auto_20230505_2048"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OnderwerpAlias",
        ),
    ]
