# Generated by Django 3.2.19 on 2024-10-09 12:06

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0017_alter_meldinggebeurtenis_gebeurtenis_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="melding",
            name="meta",
            field=utils.fields.DictJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="melding",
            name="meta_uitgebreid",
            field=utils.fields.DictJSONField(default=dict),
        ),
    ]
