# Generated by Django 3.2.18 on 2023-05-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0017_delete_onderwerpalias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meldinggebeurtenistype",
            name="melding_gebeurtenis",
        ),
        migrations.DeleteModel(
            name="TaakApplicatie",
        ),
        migrations.DeleteModel(
            name="MeldingGebeurtenisType",
        ),
    ]
