# Generated by Django 3.2.18 on 2023-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0018_auto_20230516_2132"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="resolutie",
            field=models.CharField(
                choices=[("opgelost", "Opgelost"), ("niet_opgelost", "Niet opgelost")],
                default="niet_opgelost",
                max_length=50,
            ),
        ),
    ]
