# Generated by Django 3.2.18 on 2023-05-23 08:42

import utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0019_melding_resolutie"),
    ]

    operations = [
        migrations.AddField(
            model_name="bijlage",
            name="afbeelding",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=utils.images.get_upload_path,
            ),
        ),
    ]
