# Generated by Django 3.2.19 on 2023-05-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taken", "0005_auto_20230531_1523"),
        ("meldingen", "0020_bijlage_afbeelding"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="taakopdracht",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taakopdrachten_voor_meldinggebeurtenissen",
                to="taken.taakopdracht",
            ),
        ),
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_wijziging", "Status wijziging"),
                    ("melding_aangemaakt", "Melding aangemaakt"),
                    ("taakopdracht_aangemaakt", "Taakopdracht aangemaakt"),
                    ("taakopdracht_status_wijziging", "Taakopdracht status wijziging"),
                ],
                default="standaard",
                max_length=40,
            ),
        ),
    ]
