# Generated by Django 3.2.19 on 2023-06-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0005_alter_status_naam"),
        ("taken", "0005_auto_20230531_1523"),
        ("meldingen", "0021_auto_20230531_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="taakgebeurtenis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_taakgebeurtenis",
                to="taken.taakgebeurtenis",
            ),
        ),
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="melding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_melding",
                to="meldingen.melding",
            ),
        ),
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldinggebeurtenis_voor_status",
                to="status.status",
            ),
        ),
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="taakopdracht",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meldinggebeurtenissen_voor_taakopdracht",
                to="taken.taakopdracht",
            ),
        ),
    ]
