# Generated by Django 3.2.19 on 2023-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0022_auto_20230601_1935"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signaal",
            old_name="ruwe_informatie",
            new_name="signaal_data",
        ),
        migrations.RemoveField(
            model_name="melding",
            name="melding_context",
        ),
        migrations.RemoveField(
            model_name="melding",
            name="onderwerp",
        ),
        migrations.RemoveField(
            model_name="signaal",
            name="bron",
        ),
        migrations.RemoveField(
            model_name="signaal",
            name="onderwerp",
        ),
        migrations.RemoveField(
            model_name="signaal",
            name="onderwerpen",
        ),
        migrations.RemoveField(
            model_name="signaal",
            name="origineel_aangemaakt",
        ),
        migrations.AddField(
            model_name="signaal",
            name="signaal_url",
            field=models.URLField(default="http://example.com"),
            preserve_default=False,
        ),
    ]
