# Generated by Django 3.2.19 on 2023-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meldingen", "0023_auto_20230605_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="gebruiker",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
