# Generated by Django 3.2.19 on 2024-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notificaties", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notificatie",
        ),
    ]
