# Generated by Django 3.2.19 on 2023-06-29 14:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("melders", "0001_initial"),
        ("meldingen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signaal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("signaal_url", models.URLField()),
                ("signaal_data", models.JSONField(default=dict)),
                (
                    "melder",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="melders.melder",
                    ),
                ),
                (
                    "melding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalen_voor_melding",
                        to="meldingen.melding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signaal",
                "verbose_name_plural": "Signalen",
            },
        ),
    ]
