# Generated by Django 3.2.19 on 2024-01-25 14:23

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0001_initial"),
        ("signalen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaal",
            name="externe_bron_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="signaal",
            name="externe_bron_melding_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="signaal",
            name="meta",
            field=utils.fields.DictJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="signaal",
            name="meta_uitgebreid",
            field=utils.fields.DictJSONField(default=dict),
        ),
        migrations.AddField(
            model_name="signaal",
            name="omschrijving",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="signaal",
            name="omschrijving_kort",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="signaal",
            name="onderwerpen",
            field=models.ManyToManyField(
                blank=True,
                related_name="signalen_voor_onderwerpen",
                to="aliassen.OnderwerpAlias",
            ),
        ),
        migrations.AddField(
            model_name="signaal",
            name="origineel_aangemaakt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="signaal",
            unique_together={("externe_bron_id", "externe_bron_melding_id")},
        ),
    ]
