# Generated by Django 3.2.19 on 2024-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signalen", "0002_auto_20240125_1523"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signaal",
            old_name="externe_bron_id",
            new_name="bron_id",
        ),
        migrations.RenameField(
            model_name="signaal",
            old_name="externe_bron_melding_id",
            new_name="bron_signaal_id",
        ),
        migrations.AlterUniqueTogether(
            name="signaal",
            unique_together={("bron_id", "bron_signaal_id")},
        ),
    ]
