# Generated by Django 4.2.15 on 2025-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalen", "0006_auto_20241009_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaal",
            name="omschrijving_melder",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
