# Generated by Django 3.2.19 on 2024-01-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalen", "0001_initial"),
        ("meldingen", "0005_alter_meldinggebeurtenis_locatie"),
        ("locatie", "0003_auto_20231120_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="locatie",
            name="signaal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locaties_voor_signaal",
                to="signalen.signaal",
            ),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="melding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locaties_voor_melding",
                to="meldingen.melding",
            ),
        ),
    ]
