# Generated by Django 3.2.19 on 2024-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locatie", "0004_auto_20240125_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="locatie",
            name="locatie_zoek_field",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
